[package]
name = "bandwidth-prepay-api"
version = "0.2.0"
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"

[dependencies]
solana-sdk = { git = "https://github.com/solana-labs/solana", version = "0.20.0", default-features = false }

[lib]
crate-type = ["lib"]
