[package]
name = "bandwidth-prepay-api"
version = "0.2.0"
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"

[dependencies]
solana-sdk = { git = "https://github.com/jstarry/solana", branch = "native-loader-fix", default-features = false }

[lib]
crate-type = ["lib"]
